### ISSUE TITLE
Make Hyper-V containers the default on client

### ISSUE THREAD

**Issue by enderb-ms** [Microsoft/Virtualization-Documentation#200]
When Install-ContainerHost and Update-ContainerHost are run on a client machine, docker should be set up to use Hyper-V containers by default. That way users don't have to worry about specifying the --isolation flag.

**Comment by neilpeterson** [comment]
I was hoping to use these scripts in an Azure Resource Manager template / custom script extension, to configure a container host in Azure. Can we have a script parameter / option for selecting the default? A default of Hyper-V will not work in Azure.

Also, I think this will create some confusion and support requests. Because this will limit the base OS to Nano Server, and we have limited capability / samples, etc.. Not an issue, just some thoughts.

When this goes through, please move the issue to me, I can update docs where needed.

**Comment by jhowardmsft** [comment]
Actually, I think we may be able to do better. If it's possible to reliably detect whether the daemon is running on client at startup, it could change its default to --isolation=hyperv and error out if an explicit --isolation=process is specified, as this just won't work. [More work, not actively signing up for it though :smiling_imp:]

**Comment by neilpeterson** [comment]
I apologize, I missed the comment that this was a change targeted at client, and not across all systems. I've updated my thoughts on this.

John is right, should be simple, perhaps Win32_opreatingsystem .

**Comment by mebersol** [comment]
See https://github.com/Microsoft/Virtualization-Documentation/commit/92309b8c877b0f92f9326d46942c45e2337cca59

**Comment by neilpeterson** [comment]
Change is in, closing this issue.
