### ISSUE TITLE
is container networking functioning as expected in the current version of Windows Server Containers? 

### ISSUE THREAD

**Issue by ezeeetm** [Microsoft/Virtualization-Documentation#388]
We are able to deploy single containers with no issues, using TP5 on Azure.

However, trying to create a simple asp.net > mssqlExpress stack, and --linking the containers like we can do with Linux Docker, we learn that container linking is not supported.

There is some 'container networking' [documentation ](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking?f=255&MSPPError=-2147217396)on msdn*...but no examples in those docs of one container communicating with another container (e.g. a hello world using ping?)

what we need is a working version of this (or similar) through any means:

```
docker run -d --name containerA microsoft/windowsservercore

docker run -it --link containerA:containerA --name containerB microsoft/windowsservercore ping -c 1 containerA
```

Does Windows Container Networking work well enough to demonstrate something like that today?  I realize that --link doesn't work because it isn't currently supported...but what does work to demonstrate intra-container networking on the same host?

Thanks!

**Comment by sasiezilmadhavan** [comment]
I have created two containers using the "transparent" network mode and was able to ping one container from another.  It works fine as long as both containers are in the same host.  In case of multi-host (in my case two Win 2016 TP5) where transparent network is created (in both hosts), i am NOT able ping the container running in one host say Host-A from another container which is running in host Host-B.

Does Transparent network suppose to work across hosts?  According to the MSDN [Windows Container Networking](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking#multiple-container-networks) it should be!! 

A note on environment: Both nodes are running in  Azure on the same  virtual network.

**Comment by ezeeetm** [comment]
thanks @sasiezilmadhavan

**Comment by kabracke** [comment]
Hi,

We’re glad to hear that you’re using Windows Container Networking, and sorry that this issue has been a source of confusion. It’s correct that container linking is not supported, and we have no plan to support it at this time. However, you should be able to accomplish what you need using[ Docker Compose ](https://www.docker.com/products/docker-compose)with Service Discovery. This is available in the most recent Windows 10 Insider Preview (WIP)  builds – “flights” – as well as with Windows Server 2016 GA. 

[Compose ](https://docs.docker.com/compose/overview/)is the tool that we recommend using for multi-container applications/networks. It’s designed to streamline the process of defining application services so that they run together and have connectivity; by default, Compose sets up a network for the services that you define, and makes each Container reachable/discoverable by every other Container on the default network. [The documentation on Networking in Compose ](https://docs.docker.com/compose/networking/)should be a good jumping off point for you. There you’ll find more context for how Compose enables your apps to communicate with each other using a default network, and you’ll also find direction on how to specify custom networks (custom networks can be used for intra-container communication, as well as to connect your services to external networks). 

**Please do note, however, that Compose Service Discovery only works for NAT at this time. We also support only one NAT network per Container host at this time.** Refer to the [WinNAT capabilities and limitations blog](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/) for more details.


Here’s a sample of the command that you’ll use in your Compose file to configure your containers to join a pre-existing network; you will need to use the external option:

networks:
  default:
    external:
      name: my-pre-existing-nat-network


We hope this helps, and don’t hesitate to let us know if you have any further questions!

--Kallie B.

**Comment by friism** [comment]
@ezeeetm you can also check out the compose example mentioned at the bottom of this blog post: https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
