### ISSUE TITLE
Missing ContainerSetup.ps1

### ISSUE THREAD

**Issue by cniweb** [Microsoft/Virtualization-Documentation#457]
The installation gide for Container PowerShell Cmdlets is missing:
https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/inplace_setup
and 
https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/manage_powershell

The URI for ContainerSetup.ps1: http://aka.ms/setupcontainers is also missing!

Thanks,
Chris

**Comment by PatrickLang** [comment]
Where were these linked from? The table of contents on the left of the site points to https://github.com/Microsoft/Docker-PowerShell which has the right setup steps

**Comment by cniweb** [comment]
You can found it here:
https://github.com/search?q=http%3A%2F%2Faka.ms%2Fsetupcontainers&ref=reposearch&type=Code&utf8=%E2%9C%93

**Comment by PatrickLang** [comment]
Ah, I see. We reorganized the documentation and also deprecated that script since it was specific to the technical preview. It's best to always link to http://aka.ms/windowscontainers as a durable link because things change frequently. We're aiming to reduce duplication between that site and docs.docker.com, so links will probably break again at some point.

One of these guides should have the install steps you need:
[Windows Server 2016](https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server)
or
[Windows 10](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)

**Comment by cniweb** [comment]
Hi @PatrickLang,

but the link http://aka.ms/windowscontainers do not work!

Chris

**Comment by rs38** [comment]
It does here
