### ISSUE TITLE
Debug-ContainerHost.ps1 does not show logs 

### ISSUE THREAD

**Issue by StefanScherer** [Microsoft/Virtualization-Documentation#502]
After working with a Win2016 Docker VM I saw a lot of errors in event log. I tried to extract them with the `Debug-ContainerHost.ps1` but got no messages, the csv files is also empty.

![bildschirmfoto 2016-11-28 um 22 58 37](https://cloud.githubusercontent.com/assets/207759/20688149/eab2717a-b5bf-11e6-8b09-4c18c5ea820f.png)

It seems that the dockerd in my VM is not registered to the EventLog service, the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker` is missing.

We should add a check if the registry key is missing.
Is it still possible to extract the event log messages in this case?

**Comment by PatrickLang** [comment]
Hmm, I wonder if this is a recent bug. Did you create the service with `dockerd.exe --register-service` ? It should have created that regkey

**Comment by StefanScherer** [comment]
I've started the available Win2016 Datacenter + Containers VM template in Azure, then copied the script [update-docker-rc.ps1](https://github.com/StefanScherer/docker-windows-box/blob/master/swarm-mode/scripts/update-docker-rc.ps1) into a PowerShell terminal to update to 1.13.0-rc2. But this script only stops and starts the service.
I haven't checked if the previous version of dockerd was correctly registered.

**Comment by PatrickLang** [comment]
@enderb-ms can you look at this?

@friism have you seen any issues like this?

**Comment by enderb-ms** [comment]
@StefanScherer You're right that the issue is that docker is not registered in the EventLog service. You can extract the event logs by creating a file called "docker-events.reg" with these contents:

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker]
"CustomSource"=dword:00000001
"EventMessageFile"="C:\\Program Files\\docker\\dockerd.exe"
"TypesSupported"=dword:00000007
`
After you run that, the debug script should be able to extract the event logs.

We are now looking into why it wasn't registered in the EventLog service, and we'll add a check to the debug script. Thanks for bringing this to our attention!

**Comment by StefanScherer** [comment]
Fixed with #503
